### ISSUE TITLE
Effect Enhancements

### ISSUE THREAD

**Issue by scottcl88** [scottcl88/MMM-DynamicWeather#2]
Add following options to effects:

- [x] More directions such as "left to right", "right to left", "center"
- [x] Allow for multiple weather codes
- [x] Show on holidays
- [x] Allow for recurrence (yearly, monthly, weekly, weekends, weekdays, etc.)

**Comment by RLewis8** [comment]
Add Animation speed.

**Comment by RLewis8** [comment]
It gets a little busy with both the weather/snow) running at the same time as the holiday images.  
Need an option to run Sequentially (i.e. run the holiday stream after the weather stream).

**Comment by scottcl88** [comment]
> It gets a little busy with both the weather/snow) running at the same time as the holiday images.
> Need an option to run Sequentially (i.e. run the holiday stream after the weather stream).

#11 - done

**Comment by scottcl88** [comment]
Complete - closing main issue.
