### ISSUE TITLE
missing sun sign

### ISSUE THREAD

**Issue by supersinus** [scottcl88/MMM-DynamicWeather#38]
Hi
I really love your module - would ist be possible to show also the sun? This would be great, because I live in Austria and we would be happy to see also the positive weather here, because this is not so common... - lol
I really would appreciate it very much to see it too

**Comment by citadella** [comment]
I'm sure this is doable within the current framework-I'm having a look at the code to modify it myself but probably best left for the proper dev to do...

**Comment by supersinus** [comment]
👍

**Comment by scottcl88** [comment]
@supersinus I was actually working on this, just pushed a new version with a couple of images as options. If `weatherCode == 800` for clear skies, it will display given `hideSun` is set to false.

@citadella Thanks for responding to the issue first. And by all means, if you have a solution or something better, please contribute, I'd love to see it.

**Comment by supersinus** [comment]
thank you so much - i am just installing it :-)

**Comment by citadella** [comment]
Beat to the punch-thanks @scottcl88
