### ISSUE TITLE
MM Black Screen with 'Electron' window showing

### ISSUE THREAD

**Issue by iamevl** [scottcl88/MMM-DynamicWeather#45]
**Have you tried all steps under [Troublehsooting](https://github.com/scottcl88/MMM-DynamicWeather/wiki/Troubleshooting)?**
Yes

**Describe the bug**
Installed DynamicWeather onto my MM and did an NPM install in the module folder for good measure. Added module config into my config file. Then a restart of the mm.sh caused a blank black screen with the title 'ELECTRON'

**Configuration**
`		{
			module: 'MMM-DynamicWeather',
			position: 'fullscreen_above',
			config: { // See https://github.com/scottcl88/MMM-DynamicWeather for more information.
				  api_key: "*******************************",
				  locationID: "8224783",
				  effects: [
				   {
					month: "2",
					day: "14",
					year: "2022",
					images: ["heart1.png", "heart2.png"],
					direction: "up"
				   }
				  ],
				 }
		},`

**Expected behavior**
Expected module to load

**Screenshots**
![image](https://user-images.githubusercontent.com/41927264/139143280-e2a22859-4029-445b-bf5f-8820fd16e671.png)

**Additional context**
Raspbian Stretch with MM current version as at today

**Comment by sdetweil** [comment]
just do the npm install request , commit the package.json and and push it.. then users won't have this problem

**Comment by scottcl88** [comment]
I just pushed a fix for this, it should work now. Thanks all for the help, closing.

**Comment by sdetweil** [comment]
also need to update the readme as users need to do the npm install now in the module folder after the git clone
