### ISSUE TITLE
Latest pull breaks and give api error

### ISSUE THREAD

**Issue by gregimagines** [scottcl88/MMM-DynamicWeather#49]
I pulled the recent changes (a week ago now) that implemented the OpenWeather API 3.0 feature. The module has stopped working since then. I have gone through and updated my OpenWeather account and was forced to provide a credit card to get 3.0 access on my api, but the module is not working with it. Here is the output when the module and magic mirror starts up:
[DynamicWeather-ERROR.txt](https://github.com/scottcl88/MMM-DynamicWeather/files/15153045/DynamicWeather-ERROR.txt)

**Comment by scottcl88** [comment]
This was a mistaken update from #48. Per the OpenWeather documentation [here](https://openweathermap.org/one-call-transfer#intro), only the One-Call API is changing and requires a credit card. The module is only using the [Current Weather API](https://openweathermap.org/current), and should remain unchanged and free. I've reverted those changes in #50, it should work again, but you may need to review your subscription for a valid current weather api key.
