### ISSUE TITLE
Multi-Day Effects

### ISSUE THREAD

**Issue by ggillis-ewtn** [scottcl88/MMM-DynamicWeather#54]
I love the ability to add effect images on certain days. My kids were so excited when I pulled out some Halloween ones on the day with pumpkins, bats, candy, etc. I was setting up some more for Thanksgiving and Christmas, and thought it would be nice to have the ability to display them across more than one day. (Maybe you can but I didn't see it specified and it seems like selecting the month and day require a single value. Can you do an array with day: "[1-12]"?)

Would love to have some tiny Santa hats, reindeer, presents floating across the screen for the majority of December with a few days off for a birthday or Christmas (has it's own images). 
month: 12,
day: "1-14, 16-24"
This would eliminate having to enter the same set of images 20 times each month and bloating the config file.

Additional twist, have the ability to add as time goes on. Set an image to run dec 26-jan 6, another image to display the 27-6 (with the first still visible). So instead of adding incrementally more images each consecutive day, they would just be one image per day, but would still display the previous day(s). So you slowly add a new image each day for the 12 days of Christmas. Obviously this could be for any holiday or theme, but with Christmas coming it's on my mind to start planning before chaos hits and seems the most useful.

**Comment by scottcl88** [comment]
@ggillis-ewtn  I thought this was a great idea! I've added it to the latest version. There is a separate option called "dateRange" for each effect that takes a string array in the format "YYYY-MM-DD to YYYY-MM-DD". Example: "2024-12-01 to 2024-12-25" for December 1, 2024 to December 25, 2024.

As far as the additional twist idea with adding images, I didn't quite understand and would need to figure out how that should work in this configuration.
